-- DROP SCHEMA public;
-- Schema "public" already exists in PostgreSQL by default, no need to create it

-- Note: Sequences are automatically created by PostgreSQL when using GENERATED BY DEFAULT AS IDENTITY
-- No need to create them explicitly

-- public.products definition

-- Drop table

-- DROP TABLE public.products;

CREATE TABLE IF NOT EXISTS public.products (
                                 active bool NOT NULL,
                                 price numeric(38, 2) NOT NULL,
                                 stock int4 NULL,
                                 created_at timestamp(6) NOT NULL,
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 updated_at timestamp(6) NOT NULL,
                                 description varchar(1000) NULL,
                                 brand varchar(255) NULL,
                                 category varchar(255) NULL,
                                 image_url varchar(255) NULL,
                                 "name" varchar(255) NOT NULL,
                                 CONSTRAINT products_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE IF NOT EXISTS public.users (
                              created_at timestamp(6) NOT NULL,
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              updated_at timestamp(6) NOT NULL,
                              email varchar(255) NOT NULL,
                              first_name varchar(255) NULL,
                              last_name varchar(255) NULL,
                              "password" varchar(255) NOT NULL,
                              phone varchar(255) NULL,
                              "role" varchar(255) NULL,
                              CONSTRAINT users_email_key UNIQUE (email),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


-- public.carts definition

-- Drop table

-- DROP TABLE public.carts;

CREATE TABLE IF NOT EXISTS public.carts (
                              created_at timestamp(6) NOT NULL,
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              updated_at timestamp(6) NOT NULL,
                              user_id int8 NOT NULL,
                              CONSTRAINT carts_pkey PRIMARY KEY (id),
                              CONSTRAINT carts_user_id_key UNIQUE (user_id),
                              CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE IF NOT EXISTS public.orders (
                               total_price numeric(38, 2) NOT NULL,
                               created_at timestamp(6) NOT NULL,
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               updated_at timestamp(6) NOT NULL,
                               user_id int8 NOT NULL,
                               billing_address varchar(255) NULL,
                               email varchar(255) NULL,
                               phone varchar(255) NULL,
                               shipping_address varchar(255) NULL,
                               status varchar(255) NOT NULL,
                               CONSTRAINT orders_pkey PRIMARY KEY (id),
                               CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id)
);


-- public.cart_items definition

-- Drop table

-- DROP TABLE public.cart_items;

CREATE TABLE IF NOT EXISTS public.cart_items (
                                   quantity int4 NOT NULL,
                                   cart_id int8 NOT NULL,
                                   created_at timestamp(6) NOT NULL,
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   product_id int8 NOT NULL,
                                   updated_at timestamp(6) NOT NULL,
                                   CONSTRAINT cart_items_pkey PRIMARY KEY (id),
                                   CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id),
                                   CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id)
);


-- public.order_items definition

-- Drop table

-- DROP TABLE public.order_items;

CREATE TABLE IF NOT EXISTS public.order_items (
                                    quantity int4 NOT NULL,
                                    total_price numeric(38, 2) NOT NULL,
                                    unit_price numeric(38, 2) NOT NULL,
                                    created_at timestamp(6) NOT NULL,
                                    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    order_id int8 NOT NULL,
                                    product_id int8 NOT NULL,
                                    CONSTRAINT order_items_pkey PRIMARY KEY (id),
                                    CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id),
                                    CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES public.products(id)
);